# Generated by Django 5.0.14 on 2025-11-20 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick', '0005_alter_quickstudentreceipt_amount_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick.academicyear', verbose_name='الفصل الدراسي'),
        ),
    ]
