# Generated by Django 5.0.14 on 2025-11-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_academic_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
