# Generated by Django 5.0.14 on 2025-11-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name'], 'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
    ]
