# Generated by Django 4.2.27 on 2025-12-12 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإنذار')),
                ('details', models.TextField(blank=True, verbose_name='تفاصيل الإنذار')),
                ('severity', models.CharField(choices=[('notice', 'تنبيه'), ('warning', 'إنذار'), ('critical', 'إنذار نهائي')], default='warning', max_length=20, verbose_name='درجة الإنذار')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'إنذار أكاديمي',
                'verbose_name_plural': 'إنذارات أكاديمية',
                'ordering': ['-created_at'],
            },
        ),
    ]
