# Generated by Django 4.2.30 on 2026-07-07 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0005_studentwarning'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStaffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الكتابة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'ملاحظة الموظفين',
                'verbose_name_plural': 'ملاحظات الموظفين',
                'ordering': ['-created_at'],
            },
        ),
    ]
