# Generated by Django 6.0.4 on 2026-05-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0003_journal_entry_transfer'),
        ('academic_years', '0003_journalentrytransferbatch_journalentrytransferitem'),
    ]

    operations = [
    ]
