# Generated by Django 5.0.14 on 2025-11-18 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_errors', models.IntegerField(default=0)),
                ('error_404_count', models.IntegerField(default=0)),
                ('error_403_count', models.IntegerField(default=0)),
                ('error_500_count', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('most_common_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'تحليل الأخطاء',
                'verbose_name_plural': 'تحليلات الأخطاء',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('suspicious_login', 'تسجيل دخول مشبوه'), ('brute_force', 'هجوم القوة الغاشمة'), ('sql_injection', 'محاولة حقن SQL'), ('xss', 'هجوم XSS'), ('file_inclusion', 'محاولة تضمين ملف'), ('directory_traversal', 'محاولة تجاوز الدليل')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تنبيه أمني',
                'verbose_name_plural': 'التنبيهات الأمنية',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='errorlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='severity',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['error_code', 'timestamp'], name='errors_erro_error_c_7ce101_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='errors_erro_ip_addr_801d73_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['user', 'timestamp'], name='errors_erro_user_id_e5735a_idx'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
