# Generated by Django 5.0.14 on 2025-11-18 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0002_erroranalytics_securityalert_errorlog_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField()),
                ('location_data', models.JSONField(default=dict)),
                ('device_info', models.JSONField(default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('session_count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'تتبع مستخدم',
                'verbose_name_plural': 'تتبع المستخدمين',
            },
        ),
        migrations.AddField(
            model_name='erroranalytics',
            name='average_response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='erroranalytics',
            name='most_common_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='erroranalytics',
            name='unique_countries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='asn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='browser_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='continent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='device_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='device_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='is_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='is_tablet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='isp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='os_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='reverse_dns',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='stack_trace',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='timezone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='alert_type',
            field=models.CharField(choices=[('suspicious_login', 'تسجيل دخول مشبوه'), ('brute_force', 'هجوم القوة الغاشمة'), ('sql_injection', 'محاولة حقن SQL'), ('xss', 'هجوم XSS'), ('file_inclusion', 'محاولة تضمين ملف'), ('directory_traversal', 'محاولة تجاوز الدليل'), ('malware_detected', 'برنامج ضار مكتشف'), ('data_breach_attempt', 'محاولة اختراق بيانات')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['country', 'timestamp'], name='errors_erro_country_26f167_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['severity', 'timestamp'], name='errors_erro_severit_a005cf_idx'),
        ),
        migrations.AddField(
            model_name='usertracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usertracking',
            unique_together={('user', 'ip_address')},
        ),
    ]
