# Generated by Django 4.2.27 on 2026-03-12 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('errors', '0003_usertracking_erroranalytics_average_response_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('middleware', 'Middleware'), ('frontend', 'Frontend Telemetry'), ('manual', 'Manual'), ('report', 'Report')], default='middleware', max_length=20)),
                ('category', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('threat_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('closed', 'Closed')], default='open', max_length=20)),
                ('username_snapshot', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fingerprint_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('attack_tool', models.CharField(blank=True, max_length=64)),
                ('is_known_bot', models.BooleanField(default=False)),
                ('is_new_ip_for_user', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('html_snapshot', models.TextField(blank=True)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_query', models.JSONField(blank=True, default=dict)),
                ('request_post', models.JSONField(blank=True, default=dict)),
                ('forensic_context', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_count', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fingerprint_hash', models.CharField(blank=True, max_length=64)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='errors.securityincident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityBlocklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('ip', 'IP Address'), ('fingerprint', 'Fingerprint'), ('user', 'User')], max_length=20)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_match_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_security_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('html', 'HTML Snapshot'), ('upload_metadata', 'Upload Metadata'), ('frontend_telemetry', 'Frontend Telemetry'), ('screenshot', 'Screenshot'), ('headers', 'Headers'), ('note', 'Note')], max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('text_content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='security_artifacts/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='errors.securityincident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['status', 'severity', 'detected_at'], name='errors_secu_status_9dbab1_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['ip_address', 'detected_at'], name='errors_secu_ip_addr_dd9981_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['category', 'detected_at'], name='errors_secu_categor_b2428c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'created_at'], name='errors_secu_event_t_1016e3_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['ip_address', 'created_at'], name='errors_secu_ip_addr_99c926_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securityblocklist',
            unique_together={('target_type', 'value')},
        ),
    ]
