# Generated by Django 4.2.27 on 2026-03-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0004_securityincident_securityevent_securityblocklist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='مركز الأمن - معهد اليمان', max_length=255)),
                ('brand_short', models.CharField(default='مركز الأمن', max_length=120)),
                ('sender_name', models.CharField(default='مركز الأمن - معهد اليمان', max_length=255)),
                ('support_email', models.EmailField(default='mhmadwerc8@gmail.com', max_length=254)),
                ('alert_recipient', models.EmailField(default='thaaeralmasre98@gmail.com', max_length=254)),
                ('dashboard_url', models.URLField(blank=True, default='http://127.0.0.1:8000/security/')),
                ('logo_url', models.URLField(blank=True)),
                ('subject_prefix', models.CharField(default='[مركز الأمن] ', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'هوية البريد الأمني',
                'verbose_name_plural': 'هويات البريد الأمني',
            },
        ),
    ]
