# Generated by Django 5.0.14 on 2025-11-18 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_costcenter_actual_annual_spent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفصل الدراسي')),
                ('year', models.CharField(max_length=9, verbose_name='السنة الدراسية (مثال: 2024-2025)')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الفصل الدراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'ordering': ['-year', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='QuickCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدورة')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالعربية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('course_type', models.CharField(choices=[('SCIENCE', 'علمي'), ('LITERARY', 'أدبي'), ('NINTH', 'تاسع'), ('PREPARATORY', 'تمهيدي'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع الدورة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration_weeks', models.PositiveIntegerField(verbose_name='المدة بالأسابيع')),
                ('hours_per_week', models.PositiveIntegerField(default=10, verbose_name='عدد الساعات أسبوعياً')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick.academicyear', verbose_name='الفصل الدراسي')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.costcenter', verbose_name='مركز التكلفة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دورة سريعة',
                'verbose_name_plural': 'الدورات السريعة',
                'ordering': ['academic_year', 'course_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuickStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('student_type', models.CharField(choices=[('REGULAR', 'طالب نظامي'), ('QUICK', 'طالب سريع')], default='QUICK', max_length=10, verbose_name='نوع الطالب')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick.academicyear', verbose_name='الفصل الدراسي')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='حساب الطالب')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طالب سريع',
                'verbose_name_plural': 'طلاب الدورات السريعة',
                'ordering': ['academic_year', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='QuickEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقد'), ('BANK', 'بنك'), ('CARD', 'بطاقة'), ('TRANSFER', 'تحويل')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick.quickcourse', verbose_name='الدورة')),
                ('enrollment_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_enrollments', to='accounts.journalentry', verbose_name='قيد التسجيل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick.quickstudent', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل طالب سريع',
                'verbose_name_plural': 'تسجيلات الطلاب السريعين',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
