# Generated by Django 5.0.14 on 2025-11-18 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date'], 'verbose_name': 'فصل دراسي', 'verbose_name_plural': 'فصول دراسية'},
        ),
        migrations.AlterModelOptions(
            name='quickcourse',
            options={'ordering': ['-created_at'], 'verbose_name': 'دورة سريعة', 'verbose_name_plural': 'دورات سريعة'},
        ),
        migrations.AlterModelOptions(
            name='quickenrollment',
            options={'verbose_name': 'تسجيل سريع', 'verbose_name_plural': 'تسجيلات سريعة'},
        ),
        migrations.AlterModelOptions(
            name='quickstudent',
            options={'ordering': ['-created_at'], 'verbose_name': 'طالب سريع', 'verbose_name_plural': 'طلاب سريعين'},
        ),
        migrations.RemoveField(
            model_name='quickenrollment',
            name='enrollment_journal_entry',
        ),
        migrations.RemoveField(
            model_name='quickenrollment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='quickenrollment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='quickenrollment',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='quickstudent',
            name='account',
        ),
        migrations.RemoveField(
            model_name='quickstudent',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإقفال'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مقفل بواسطة'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='مقفول'),
        ),
        migrations.AddField(
            model_name='quickenrollment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المبلغ الصافي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quickstudent',
            name='student',
            field=models.OneToOneField(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='quick_student_profile', to='students.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفصل'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(max_length=20, verbose_name='السنة الدراسية'),
        ),
        migrations.AlterField(
            model_name='quickcourse',
            name='course_type',
            field=models.CharField(choices=[('INTENSIVE', 'مكثفة'), ('REGULAR', 'عادية'), ('WEEKEND', 'نهاية أسبوع')], default='REGULAR', max_length=20, verbose_name='نوع الدورة'),
        ),
        migrations.AlterField(
            model_name='quickcourse',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='quickcourse',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4, verbose_name='المدة (أسابيع)'),
        ),
        migrations.AlterField(
            model_name='quickcourse',
            name='hours_per_week',
            field=models.PositiveIntegerField(default=6, verbose_name='ساعات أسبوعياً'),
        ),
        migrations.AlterField(
            model_name='quickenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quick.quickcourse'),
        ),
        migrations.AlterField(
            model_name='quickenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quick.quickstudent'),
        ),
        migrations.AlterField(
            model_name='quickstudent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='quickstudent',
            name='email',
            field=models.EmailField(blank=True, default=0, max_length=254, verbose_name='البريد الإلكتروني'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quickstudent',
            name='student_type',
            field=models.CharField(choices=[('QUICK', 'سريع'), ('REGULAR', 'نظامي')], default='QUICK', max_length=20, verbose_name='نوع الطالب'),
        ),
    ]
