# Generated by Django 5.0.14 on 2025-11-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick', '0002_alter_academicyear_options_alter_quickcourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickenrollment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقدي'), ('BANK', 'تحويل بنكي'), ('CREDIT', 'بطاقة ائتمان')], default='CASH', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='quickenrollment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='quickenrollment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ الصافي'),
        ),
    ]
