# Generated by Django 5.0.14 on 2025-11-18 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentreceipt_quick_enrollment'),
        ('quick', '0003_quickenrollment_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickStudentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('student_name', models.CharField(max_length=200, verbose_name='اسم الطالب')),
                ('course_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الدورة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK', 'تحويل بنكي'), ('CREDIT', 'بطاقة ائتمان')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الإيصال')),
                ('is_printed', models.BooleanField(default=False, verbose_name='تم الطباعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick.quickcourse', verbose_name='الدورة السريعة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='قيد اليومية')),
                ('quick_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick.quickenrollment', verbose_name='التسجيل السريع')),
                ('quick_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick.quickstudent', verbose_name='الطالب السريع')),
            ],
            options={
                'verbose_name': 'إيصال طالب سريع',
                'verbose_name_plural': 'إيصالات الطلاب السريعين',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
