# Generated by Django 5.0.14 on 2025-11-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick', '0004_quickstudentreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickstudentreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='quickstudentreceipt',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قيمة الخصم'),
        ),
        migrations.AlterField(
            model_name='quickstudentreceipt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
    ]
