# Generated by Django 5.0.14 on 2025-11-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick', '0005_alter_quickstudentreceipt_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_open_ended',
            field=models.BooleanField(default=False, verbose_name='مفتوح غير مسكر'),
        ),
    ]
