# Generated by Django 4.2.27 on 2026-03-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick', '0007_quickstudent_course_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickcourse',
            name='course_type',
            field=models.CharField(choices=[('INTENSIVE', 'مكثفة'), ('REGULAR', 'عادية'), ('WEEKEND', 'نهاية أسبوع'), ('EXAM', 'امتحانية')], default='REGULAR', max_length=20, verbose_name='نوع الدورة'),
        ),
    ]
