# Generated by Django 4.2.27 on 2026-04-01 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quick', '0009_quickreceiptprintjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickCourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الكلاس')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='رمز الكلاس')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='السعة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('total_days', models.PositiveIntegerField(default=1, verbose_name='عدد الأيام')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('meeting_days', models.CharField(blank=True, max_length=200, verbose_name='أيام الدوام')),
                ('room_name', models.CharField(blank=True, max_length=120, verbose_name='القاعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quick.quickcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quick_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'كلاس دورة سريعة',
                'verbose_name_plural': 'كلاسات الدورات السريعة',
                'ordering': ['start_date', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuickCourseSessionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_session_assignments', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_assignment', to='quick.quickenrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_enrollments', to='quick.quickcoursesession')),
            ],
            options={
                'verbose_name': 'توزيع طالب على كلاس سريع',
                'verbose_name_plural': 'توزيعات الطلاب على الكلاسات السريعة',
                'ordering': ['session__start_date', 'session__start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuickCourseSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='تاريخ الحضور')),
                ('day_number', models.PositiveIntegerField(default=1, verbose_name='رقم اليوم')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'غياب مبرر')], default='present', max_length=20, verbose_name='الحالة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quick_attendance', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_session_attendance', to='quick.quickenrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='quick.quickcoursesession')),
            ],
            options={
                'verbose_name': 'حضور كلاس سريع',
                'verbose_name_plural': 'حضور الكلاسات السريعة',
                'ordering': ['-attendance_date', 'session__start_time', 'id'],
                'unique_together': {('session', 'enrollment', 'attendance_date')},
            },
        ),
    ]
