# Generated by Django 4.2.27 on 2026-04-01 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0002_initial'),
        ('quick', '0011_quickcoursesession_end_date_and_min_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickcoursesession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_sessions', to='classroom.classroom', verbose_name='القاعة'),
        ),
        migrations.AlterField(
            model_name='quickcoursesession',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='الحد الأقصى'),
        ),
        migrations.CreateModel(
            name='QuickCourseTimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الخيار')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('meeting_days', models.CharField(blank=True, max_length=200, verbose_name='أيام الدوام')),
                ('min_capacity', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى')),
                ('max_capacity', models.PositiveIntegerField(default=0, verbose_name='الحد الأقصى')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='الأولوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_options', to='quick.quickcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quick_time_options', to=settings.AUTH_USER_MODEL)),
                ('preferred_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_time_options', to='classroom.classroom', verbose_name='القاعة المفضلة')),
            ],
            options={
                'verbose_name': 'وقت متاح للدورة السريعة',
                'verbose_name_plural': 'الأوقات المتاحة للدورات السريعة',
                'ordering': ['priority', 'start_date', 'start_time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quickcoursesession',
            name='time_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_sessions', to='quick.quickcoursetimeoption'),
        ),
    ]
