# Generated by Django 6.0.4 on 2026-05-31 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick', '0015_quickcoursewithdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSessionExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(choices=[('alkhoutwa', 'الخطوة'), ('alidrisi', 'الادريسي'), ('khalil', 'خليل')], max_length=50, verbose_name='المعهد')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستيراد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الاستيراد بواسطة')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_imports', to='quick.quickcoursesession', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': 'استيراد طلاب إكسل',
                'verbose_name_plural': 'استيرادات طلاب إكسل',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickSessionExcelStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الطالب')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('excel_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='quick.quicksessionexcelimport', verbose_name='دفعة الاستيراد')),
            ],
            options={
                'verbose_name': 'طالب مستورد من إكسل',
                'verbose_name_plural': 'طلاب مستوردون من إكسل',
                'ordering': ['name'],
            },
        ),
    ]
