# Generated by Django 6.0.4 on 2026-07-10 19:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0012_teacher_is_partner_teacher_partnership_percentage_and_more'),
        ('quick', '0016_quicksessionexcelimport_quicksessionexcelstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickcoursesession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_sessions', to='employ.teacher', verbose_name='المدرس'),
        ),
        migrations.AddField(
            model_name='quickcoursesession',
            name='teacher_pay_type',
            field=models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'نسبة من رسوم الطلاب')], default='fixed', max_length=20, verbose_name='نوع استحقاق المعلم'),
        ),
        migrations.AddField(
            model_name='quickcoursesession',
            name='teacher_pay_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='قيمة استحقاق المعلم'),
        ),
    ]
