# Generated by Django 5.0.14 on 2025-11-08 22:52

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='رقم الهاتف')),
                ('branches', models.CharField(help_text='الفروع التي يدرّسها المدرّس مفصولة بفاصلة', max_length=100, verbose_name='الفروع')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ التعيين')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='الأجر عن كل حصة دراسية', max_digits=10, null=True, verbose_name='أجر الساعة')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='يستخدم مع نوع الراتب الشهري أو المختلط', max_digits=10, null=True, verbose_name='راتب شهري ثابت')),
                ('salary_type', models.CharField(choices=[('hourly', 'ساعي'), ('monthly', 'شهري ثابت'), ('mixed', 'مختلط (شهري + ساعي)')], default='hourly', max_length=20, verbose_name='نوع الراتب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مدرّس',
                'verbose_name_plural': 'مدرّسون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='راتب شهري')),
                ('position', models.CharField(choices=[('admin', 'مسؤول'), ('accountant', 'محاسب'), ('hr', 'موارد بشرية'), ('staff', 'موظف')], default='staff', max_length=50, verbose_name='الوظيفة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('يومية', 'يومية'), ('طارئة', 'طارئة'), ('مرضية', 'مرضية')], max_length=20, verbose_name='نوع الإجازة')),
                ('reason', models.TextField(verbose_name='سبب الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء الإجازة')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الإجازة')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='تاريخ تقديم الطلب')),
                ('is_replacement_secured', models.BooleanField(default=False, verbose_name='تم تأمين البديل')),
                ('manager_opinion', models.TextField(blank=True, null=True, verbose_name='رأي المدير')),
                ('general_manager_opinion', models.TextField(blank=True, null=True, verbose_name='رأي المدير العام')),
                ('status', models.CharField(choices=[('معلقة', 'معلقة'), ('موافق', 'موافق'), ('غير موافق', 'غير موافق')], default='معلقة', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='employ.employee')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'الإجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('students_view', 'عرض قائمة الطلاب'), ('students_create', 'إضافة طالب جديد'), ('students_edit', 'تعديل بيانات الطلاب'), ('students_delete', 'حذف الطلاب'), ('students_profile', 'عرض ملف الطالب'), ('students_receipt', 'قطع إيصالات الطلاب'), ('students_statement', 'كشف حساب الطالب'), ('students_register_course', 'تسجيل الطالب في دورة'), ('students_withdraw', 'سحب الطالب من دورة'), ('students_export', 'تصدير بيانات الطلاب'), ('teachers_view', 'عرض قائمة المدرسين'), ('teachers_create', 'إضافة مدرس جديد'), ('teachers_edit', 'تعديل بيانات المدرسين'), ('teachers_delete', 'حذف المدرسين'), ('teachers_profile', 'عرض ملف المدرس'), ('teachers_salary', 'إدارة رواتب المدرسين'), ('teachers_salary_pay', 'دفع رواتب المدرسين'), ('teachers_salary_accrual', 'إنشاء قيود استحقاق الرواتب'), ('teachers_advance', 'إدارة سلف المدرسين'), ('teachers_advance_create', 'إنشاء سلفة للمدرس'), ('attendance_view', 'عرض سجل الحضور'), ('attendance_take', 'تسجيل حضور الطلاب'), ('attendance_edit', 'تعديل سجل الحضور'), ('attendance_export', 'تصدير سجل الحضور'), ('attendance_teacher_view', 'عرض حضور المدرسين'), ('attendance_teacher_take', 'تسجيل حضور المدرسين'), ('attendance_teacher_export', 'تصدير حضور المدرسين'), ('classroom_view', 'عرض قائمة الشعب'), ('classroom_create', 'إنشاء شعبة جديدة'), ('classroom_edit', 'تعديل الشعب'), ('classroom_delete', 'حذف الشعب'), ('classroom_assign', 'تعيين الطلاب للشعب'), ('classroom_students', 'عرض طلاب الشعبة'), ('classroom_subjects', 'إدارة مواد الشعبة'), ('classroom_export', 'تصدير بيانات الشعب'), ('grades_view', 'عرض العلامات'), ('grades_edit', 'تعديل العلامات'), ('grades_export', 'تصدير العلامات لإكسل'), ('grades_print', 'طباعة كشوف العلامات'), ('grades_custom_print', 'طباعة مخصصة للعلامات'), ('courses_view', 'عرض قائمة المواد'), ('courses_create', 'إضافة مادة جديدة'), ('courses_edit', 'تعديل المواد'), ('courses_delete', 'حذف المواد'), ('courses_assign_teachers', 'تعيين المدرسين للمواد'), ('accounting_dashboard', 'لوحة تحكم المحاسبة'), ('accounting_view', 'عرض النظام المحاسبي'), ('accounting_entries', 'إنشاء وتعديل قيود اليومية'), ('accounting_entries_post', 'ترحيل قيود اليومية'), ('accounting_accounts', 'إدارة دليل الحسابات'), ('accounting_accounts_create', 'إنشاء حسابات جديدة'), ('accounting_reports', 'عرض التقارير المالية'), ('accounting_trial_balance', 'ميزان المراجعة'), ('accounting_income_statement', 'قائمة الدخل'), ('accounting_balance_sheet', 'الميزانية العمومية'), ('accounting_ledger', 'دفاتر الأستاذ'), ('accounting_receipts', 'إيصالات الطلاب'), ('accounting_receipts_create', 'إنشاء إيصالات جديدة'), ('accounting_expenses', 'إدارة المصروفات'), ('accounting_expenses_create', 'تسجيل مصروفات جديدة'), ('accounting_budgets', 'إدارة الميزانيات'), ('accounting_periods', 'الفترات المحاسبية'), ('accounting_cost_centers', 'مراكز التكلفة'), ('accounting_outstanding', 'تقارير المتبقي على الطلاب'), ('accounting_export', 'تصدير التقارير المالية'), ('hr_dashboard', 'لوحة تحكم الموارد البشرية'), ('hr_view', 'عرض قائمة الموظفين'), ('hr_create', 'تسجيل موظف جديد'), ('hr_edit', 'تعديل بيانات الموظفين'), ('hr_delete', 'حذف الموظفين'), ('hr_profile', 'عرض ملف الموظف'), ('hr_permissions', 'إدارة صلاحيات الموظفين'), ('hr_salary', 'إدارة رواتب الموظفين'), ('hr_salary_pay', 'دفع رواتب الموظفين'), ('hr_advances', 'إدارة سلف الموظفين'), ('hr_advances_create', 'إنشاء سلفة للموظف'), ('hr_vacations', 'إدارة إجازات الموظفين'), ('hr_vacations_approve', 'الموافقة على الإجازات'), ('admin_dashboard', 'الوصول للوحة التحكم الرئيسية'), ('admin_settings', 'إعدادات النظام العامة'), ('admin_users', 'إدارة المستخدمين والحسابات'), ('admin_backup', 'النسخ الاحتياطي واستعادة البيانات'), ('admin_logs', 'عرض سجلات النظام'), ('admin_database', 'إدارة قاعدة البيانات'), ('admin_maintenance', 'صيانة النظام'), ('reports_dashboard', 'لوحة تحكم التقارير'), ('reports_students', 'تقارير الطلاب وإحصائياتهم'), ('reports_students_export', 'تصدير تقارير الطلاب'), ('reports_teachers', 'تقارير المدرسين وأدائهم'), ('reports_teachers_export', 'تصدير تقارير المدرسين'), ('reports_financial', 'التقارير المالية والمحاسبية'), ('reports_financial_export', 'تصدير التقارير المالية'), ('reports_attendance', 'تقارير الحضور والغياب'), ('reports_attendance_export', 'تصدير تقارير الحضور'), ('reports_grades', 'تقارير العلامات والدرجات'), ('reports_grades_export', 'تصدير تقارير العلامات'), ('reports_custom', 'تقارير مخصصة'), ('course_accounting_view', 'عرض دورات النظام المحاسبي'), ('course_accounting_create', 'إنشاء دورة جديدة'), ('course_accounting_edit', 'تعديل الدورات'), ('course_accounting_pricing', 'إدارة أسعار الدورات'), ('inventory_view', 'عرض المخزون'), ('inventory_manage', 'إدارة المخزون'), ('assets_view', 'عرض الأصول'), ('assets_manage', 'إدارة الأصول'), ('marketing_campaigns', 'إدارة الحملات التسويقية'), ('marketing_leads', 'إدارة العملاء المحتملين'), ('marketing_analytics', 'تحليلات التسويق'), ('quality_surveys', 'استطلاعات رضا الطلاب'), ('quality_feedback', 'إدارة التغذية الراجعة'), ('quality_evaluation', 'تقييم المدرسين')], max_length=50)),
                ('is_granted', models.BooleanField(default=False, verbose_name='ممنوح')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المنح')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='employ.employee')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مُنح بواسطة')),
            ],
            options={
                'verbose_name': 'صلاحية موظف',
                'verbose_name_plural': 'صلاحيات الموظفين',
                'unique_together': {('employee', 'permission')},
            },
        ),
    ]
