# Generated by Django 5.0.14 on 2025-11-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='branch',
            field=models.CharField(choices=[('SCIENCE', 'علمي / Science'), ('LITERARY', 'أدبي / Literary'), ('NINTH', 'تاسع / Ninth Grade'), ('PREPARATORY', 'تمهيدي / Preparatory')], default=1, max_length=20, verbose_name='التخصص / Branch'),
            preserve_default=False,
        ),
    ]
