# Generated by Django 4.2.7 on 2025-12-04 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employ', '0003_alter_employeepermission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepermission',
            name='permission',
            field=models.CharField(choices=[('students_view', 'عرض قائمة الطلاب'), ('students_create', 'إضافة طالب جديد'), ('students_edit', 'تعديل بيانات الطلاب'), ('students_delete', 'حذف الطلاب'), ('students_profile', 'عرض ملف الطالب'), ('students_receipt', 'قطع إيصالات الطلاب'), ('students_statement', 'كشف حساب الطالب'), ('students_register_course', 'تسجيل الطالب في دورة'), ('students_withdraw', 'سحب الطالب من دورة'), ('students_export', 'تصدير بيانات الطلاب'), ('teachers_view', 'عرض قائمة المدرسين'), ('teachers_create', 'إضافة مدرس جديد'), ('teachers_edit', 'تعديل بيانات المدرسين'), ('teachers_delete', 'حذف المدرسين'), ('teachers_profile', 'عرض ملف المدرس'), ('teachers_salary', 'إدارة رواتب المدرسين'), ('teachers_salary_pay', 'دفع رواتب المدرسين'), ('teachers_salary_accrual', 'إنشاء قيود استحقاق الرواتب'), ('teachers_advance', 'إدارة سلف المدرسين'), ('teachers_advance_create', 'إنشاء سلفة للمدرس'), ('attendance_view', 'عرض سجل الحضور'), ('attendance_take', 'تسجيل حضور الطلاب'), ('attendance_edit', 'تعديل سجل الحضور'), ('attendance_export', 'تصدير سجل الحضور'), ('attendance_teacher_view', 'عرض حضور المدرسين'), ('attendance_teacher_take', 'تسجيل حضور المدرسين'), ('attendance_teacher_export', 'تصدير حضور المدرسين'), ('classroom_view', 'عرض قائمة الشعب'), ('classroom_create', 'إنشاء شعبة جديدة'), ('classroom_edit', 'تعديل الشعب'), ('classroom_delete', 'حذف الشعب'), ('classroom_assign', 'تعيين الطلاب للشعب'), ('classroom_students', 'عرض طلاب الشعبة'), ('classroom_subjects', 'إدارة مواد الشعبة'), ('classroom_export', 'تصدير بيانات الشعب'), ('courses_view', 'عرض قائمة المواد'), ('courses_create', 'إضافة مادة جديدة'), ('courses_edit', 'تعديل المواد'), ('courses_delete', 'حذف المواد'), ('courses_assign_teachers', 'تعيين المدرسين للمواد'), ('accounting_dashboard', 'لوحة تحكم المحاسبة'), ('accounting_view', 'عرض النظام المحاسبي'), ('accounting_entries', 'إنشاء وتعديل قيود اليومية'), ('accounting_entries_post', 'ترحيل قيود اليومية'), ('accounting_accounts', 'إدارة دليل الحسابات'), ('accounting_accounts_create', 'إنشاء حسابات جديدة'), ('accounting_reports', 'عرض التقارير المالية'), ('accounting_trial_balance', 'ميزان المراجعة'), ('accounting_income_statement', 'قائمة الدخل'), ('accounting_balance_sheet', 'الميزانية العمومية'), ('accounting_ledger', 'دفاتر الأستاذ'), ('accounting_receipts', 'إيصالات الطلاب'), ('accounting_receipts_create', 'إنشاء إيصالات جديدة'), ('accounting_expenses', 'إدارة المصروفات'), ('accounting_expenses_create', 'تسجيل مصروفات جديدة'), ('accounting_budgets', 'إدارة الميزانيات'), ('accounting_periods', 'الفترات المحاسبية'), ('accounting_cost_centers', 'مراكز التكلفة'), ('accounting_outstanding', 'تقارير المتبقي على الطلاب'), ('accounting_export', 'تصدير التقارير المالية'), ('hr_dashboard', 'لوحة تحكم الموارد البشرية'), ('hr_view', 'عرض قائمة الموظفين'), ('hr_create', 'تسجيل موظف جديد'), ('hr_edit', 'تعديل بيانات الموظفين'), ('hr_delete', 'حذف الموظفين'), ('hr_profile', 'عرض ملف الموظف'), ('hr_permissions', 'إدارة صلاحيات الموظفين'), ('hr_salary', 'إدارة رواتب الموظفين'), ('hr_salary_pay', 'دفع رواتب الموظفين'), ('hr_advances', 'إدارة سلف الموظفين'), ('hr_advances_create', 'إنشاء سلفة للموظف'), ('hr_vacations', 'إدارة إجازات الموظفين'), ('hr_vacations_approve', 'الموافقة على الإجازات'), ('admin_dashboard', 'الوصول للوحة التحكم الرئيسية'), ('admin_settings', 'إعدادات النظام العامة'), ('admin_users', 'إدارة المستخدمين والحسابات'), ('admin_backup', 'النسخ الاحتياطي واستعادة البيانات'), ('admin_logs', 'عرض سجلات النظام'), ('admin_database', 'إدارة قاعدة البيانات'), ('admin_maintenance', 'صيانة النظام'), ('reports_dashboard', 'لوحة تحكم التقارير'), ('reports_students', 'تقارير الطلاب وإحصائياتهم'), ('reports_students_export', 'تصدير تقارير الطلاب'), ('reports_teachers', 'تقارير المدرسين وأدائهم'), ('reports_teachers_export', 'تصدير تقارير المدرسين'), ('reports_financial', 'التقارير المالية والمحاسبية'), ('reports_financial_export', 'تصدير التقارير المالية'), ('reports_attendance', 'تقارير الحضور والغياب'), ('reports_attendance_export', 'تصدير تقارير الحضور'), ('reports_grades', 'تقارير العلامات والدرجات'), ('reports_grades_export', 'تصدير تقارير العلامات'), ('reports_custom', 'تقارير مخصصة'), ('course_accounting_view', 'عرض دورات النظام المحاسبي'), ('course_accounting_create', 'إنشاء دورة جديدة'), ('course_accounting_edit', 'تعديل الدورات'), ('course_accounting_pricing', 'إدارة أسعار الدورات'), ('inventory_view', 'عرض المخزون'), ('inventory_manage', 'إدارة المخزون'), ('assets_view', 'عرض الأصول'), ('assets_manage', 'إدارة الأصول'), ('marketing_campaigns', 'إدارة الحملات التسويقية'), ('marketing_leads', 'إدارة العملاء المحتملين'), ('marketing_analytics', 'تحليلات التسويق'), ('quality_surveys', 'استطلاعات رضا الطلاب'), ('quality_feedback', 'إدارة التغذية الراجعة'), ('quality_evaluation', 'تقييم المدرسين'), ('quick_students_view', 'عرض الطلاب السريعين'), ('quick_students_create', 'إضافة طالب سريع'), ('quick_students_edit', 'تعديل الطلاب السريعين'), ('quick_students_delete', 'حذف الطلاب السريعين'), ('quick_students_profile', 'عرض ملف الطالب السريع'), ('quick_students_receipt', 'قطع إيصالات الطلاب السريعين'), ('quick_students_statement', 'كشف حساب الطالب السريع'), ('quick_students_register', 'تسجيل الطالب السريع في دورة'), ('quick_students_withdraw', 'سحب الطالب السريع'), ('quick_students_refund', 'استرجاع الطالب السريع'), ('quick_students_export', 'تصدير بيانات الطلاب السريعين'), ('exams_view', 'عرض الاختبارات'), ('exams_create', 'إنشاء اختبار جديد'), ('exams_edit', 'تعديل الاختبارات'), ('exams_delete', 'حذف الاختبارات'), ('exams_grades_view', 'عرض علامات الاختبار'), ('exams_grades_edit', 'تعديل علامات الاختبار'), ('exams_export', 'تصدير نتائج الاختبار'), ('exams_print', 'طباعة نتائج الاختبار'), ('exams_stats', 'إحصائيات الاختبار'), ('accounting_quick_receipt', 'الإيصال الفوري'), ('accounting_student_withdraw', 'سحب الطالب'), ('accounting_withdrawn_students', 'عرض الطلاب المسحوبين'), ('accounting_outstanding_classroom', 'المتبقي حسب الشعبة')], max_length=50),
        ),
        migrations.CreateModel(
            name='ManualTeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('month', models.IntegerField(choices=[(1, 'كانون الثاني'), (2, 'شباط'), (3, 'آذار'), (4, 'نيسان'), (5, 'أيار'), (6, 'حزيران'), (7, 'تموز'), (8, 'آب'), (9, 'أيلول'), (10, 'تشرين الأول'), (11, 'تشرين الثاني'), (12, 'كانون الأول')], verbose_name='الشهر')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الإجمالي')),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم السلف')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الصافي المستحق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_salaries', to='employ.teacher')),
            ],
            options={
                'verbose_name': 'راتب يدوي للمدرس',
                'verbose_name_plural': 'رواتب يدوية للمدرسين',
                'ordering': ['-year', '-month'],
                'unique_together': {('teacher', 'year', 'month')},
            },
        ),
    ]
