# Generated by Django 4.2.27 on 2026-01-03 15:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0004_alter_employeepermission_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hourly_rate_literary',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Hourly Rate - Literary'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hourly_rate_ninth',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Hourly Rate - Ninth'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hourly_rate_preparatory',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Hourly Rate - Preparatory'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hourly_rate_scientific',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Hourly Rate - Scientific'),
        ),
    ]
