# Generated by Django 5.2.13 on 2026-04-21 11:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0005_teacher_hourly_rate_literary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم السياسة')),
                ('late_deduction_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='خصم التأخير لكل ساعة')),
                ('early_leave_deduction_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='خصم الخروج المبكر لكل ساعة')),
                ('absence_deduction_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, verbose_name='معامل خصم الغياب')),
                ('overtime_enabled', models.BooleanField(default=True, verbose_name='حساب الإضافي')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='نسبة الإضافي')),
                ('rounding_method', models.CharField(choices=[('none', 'بدون تقريب'), ('minute', 'تقريب للدقيقة'), ('5_minutes', 'تقريب لـ 5 دقائق'), ('15_minutes', 'تقريب لـ 15 دقيقة')], default='minute', max_length=20, verbose_name='طريقة التقريب')),
                ('holiday_handling', models.CharField(choices=[('ignore', 'تجاهل'), ('treat_as_overtime', 'إضافي'), ('treat_as_regular', 'دوام عادي')], default='ignore', max_length=20, verbose_name='التعامل مع العطل')),
                ('weekend_days', models.CharField(default='4,5', max_length=20, verbose_name='أيام العطل الأسبوعية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سياسة دوام',
                'verbose_name_plural': 'سياسات الدوام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الجهاز')),
                ('ip', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('port', models.PositiveIntegerField(default=4370, verbose_name='المنفذ')),
                ('serial', models.CharField(max_length=100, unique=True, verbose_name='الرقم التسلسلي')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='الموقع')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جهاز بصمة',
                'verbose_name_plural': 'أجهزة البصمة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم القسم')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='رمز القسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم القاعدة')),
                ('salary_type', models.CharField(choices=[('monthly', 'شهري'), ('daily', 'يومي'), ('hourly', 'بالساعة')], default='monthly', max_length=20, verbose_name='نوع الراتب')),
                ('overtime_enabled', models.BooleanField(default=True, verbose_name='احتساب الإضافي')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='نسبة الإضافي')),
                ('late_deduction_enabled', models.BooleanField(default=True, verbose_name='خصم التأخير')),
                ('absence_deduction_enabled', models.BooleanField(default=True, verbose_name='خصم الغياب')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='الضريبة %')),
                ('insurance_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='التأمين %')),
                ('max_overtime_seconds', models.PositiveIntegerField(default=0, verbose_name='الحد الأعلى للإضافي بالثواني')),
                ('max_deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الحد الأعلى للخصومات')),
                ('rounding_method', models.CharField(choices=[('none', 'بدون تقريب'), ('minute', 'تقريب للدقيقة'), ('5_minutes', 'تقريب لـ 5 دقائق'), ('15_minutes', 'تقريب لـ 15 دقيقة')], default='minute', max_length=20, verbose_name='التقريب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قاعدة راتب موظف',
                'verbose_name_plural': 'قواعد رواتب الموظفين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='اسم الشفت')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='رمز الشفت')),
                ('start_time', models.TimeField(verbose_name='وقت الدخول')),
                ('end_time', models.TimeField(verbose_name='وقت الخروج')),
                ('grace_period_minutes', models.PositiveIntegerField(default=0, verbose_name='وقت السماح بالدقائق')),
                ('required_work_seconds', models.PositiveIntegerField(default=28800, verbose_name='ساعات العمل المطلوبة بالثواني')),
                ('is_night_shift', models.BooleanField(default=False, verbose_name='دوام ليلي')),
                ('break_seconds', models.PositiveIntegerField(default=0, verbose_name='مدة الاستراحة بالثواني')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='بداية الاستراحة')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الاستراحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شفت',
                'verbose_name_plural': 'الشفتات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_user_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='معرف البصمة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='نهاية العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='بداية العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('permanent', 'دائم'), ('temporary', 'مؤقت'), ('probation', 'تجربة'), ('freelance', 'تعاقد حر')], default='permanent', max_length=20, verbose_name='نوع العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم جهة الطوارئ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف جهة الطوارئ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'على رأس العمل'), ('suspended', 'موقوف'), ('vacation', 'في إجازة'), ('terminated', 'منتهي الخدمة')], default='active', max_length=20, verbose_name='حالة الموظف'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='الرقم الوطني'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/profiles/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='attendance_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employ.attendancepolicy', verbose_name='سياسة الدوام'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employ.department', verbose_name='القسم'),
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الراتب')),
                ('deductions_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الخصومات')),
                ('overtime_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الإضافي')),
                ('advances_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='السلف')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الضريبة')),
                ('insurance_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='التأمين')),
                ('compensation_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='التعويضات')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='صافي الراتب')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employ.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مسير موظف',
                'verbose_name_plural': 'مسيرات الموظفين',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('base_salary', 'راتب أساسي'), ('attendance', 'دوام'), ('overtime', 'إضافي'), ('late_deduction', 'خصم تأخير'), ('absence_deduction', 'خصم غياب'), ('advance_deduction', 'خصم سلفة'), ('tax', 'ضريبة'), ('insurance', 'تأمين'), ('compensation', 'تعويض'), ('adjustment', 'تسوية')], max_length=30, verbose_name='النوع')),
                ('title', models.CharField(max_length=150, verbose_name='العنوان')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القيمة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('source_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع المصدر')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='employ.employeepayroll', verbose_name='المسير')),
            ],
            options={
                'verbose_name': 'سطر مسير',
                'verbose_name_plural': 'سطور المسير',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employ.employeesalaryrule', verbose_name='قاعدة الراتب'),
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='المسمى الوظيفي')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='الرمز')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to='employ.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'مسمى وظيفي',
                'verbose_name_plural': 'المسميات الوظيفية',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employ.jobtitle', verbose_name='المسمى الوظيفي'),
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الفترة')),
                ('start_date', models.DateField(verbose_name='من')),
                ('end_date', models.DateField(verbose_name='إلى')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('processing', 'قيد المعالجة'), ('closed', 'مغلق')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فترة رواتب',
                'verbose_name_plural': 'فترات الرواتب',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('start_date', 'end_date'), name='unique_payroll_period_dates')],
            },
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payrolls', to='employ.payrollperiod', verbose_name='الفترة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employ.shift', verbose_name='الشفت الافتراضي'),
        ),
        migrations.CreateModel(
            name='BiometricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=30, verbose_name='معرف المستخدم على الجهاز')),
                ('punch_time', models.DateTimeField(verbose_name='وقت البصمة')),
                ('punch_type', models.CharField(choices=[('check_in', 'دخول'), ('check_out', 'خروج'), ('break_out', 'خروج استراحة'), ('break_in', 'عودة استراحة'), ('unknown', 'غير معروف')], default='unknown', max_length=20, verbose_name='نوع الحركة')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات الخام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='employ.biometricdevice', verbose_name='الجهاز')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='employ.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل بصمة',
                'verbose_name_plural': 'سجلات البصمة',
                'ordering': ['-punch_time'],
                'constraints': [models.UniqueConstraint(fields=('device', 'device_user_id', 'punch_time', 'punch_type'), name='unique_biometric_log_event')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='دخول')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='خروج')),
                ('worked_seconds', models.PositiveIntegerField(default=0, verbose_name='العمل الفعلي بالثواني')),
                ('late_seconds', models.PositiveIntegerField(default=0, verbose_name='التأخير بالثواني')),
                ('early_leave_seconds', models.PositiveIntegerField(default=0, verbose_name='الخروج المبكر بالثواني')),
                ('overtime_seconds', models.PositiveIntegerField(default=0, verbose_name='الإضافي بالثواني')),
                ('absence_seconds', models.PositiveIntegerField(default=0, verbose_name='الغياب بالثواني')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('partial', 'دوام جزئي'), ('late', 'متأخر'), ('absent', 'غائب'), ('vacation', 'إجازة'), ('weekend', 'عطلة')], default='absent', max_length=20, verbose_name='الحالة')),
                ('source', models.CharField(default='biometric', max_length=20, verbose_name='المصدر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employ.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'دوام موظف',
                'verbose_name_plural': 'دوام الموظفين',
                'ordering': ['-date', 'employee__user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_attendance_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_job_title_per_department'),
        ),
        migrations.AddConstraint(
            model_name='employeepayroll',
            constraint=models.UniqueConstraint(fields=('employee', 'period'), name='unique_employee_payroll_per_period'),
        ),
    ]
