# Generated by Django 6.0.4 on 2026-04-21 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0006_attendancepolicy_biometricdevice_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='is_manually_adjusted',
            field=models.BooleanField(default=False, verbose_name='معدل يدويًا'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='manual_adjustment_reason',
            field=models.TextField(blank=True, verbose_name='سبب التعديل اليدوي'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المراجعة'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='review_status',
            field=models.CharField(choices=[('not_required', 'لا تحتاج مراجعة'), ('pending', 'بانتظار المراجعة'), ('justified', 'مبرر'), ('unjustified', 'غير مبرر')], default='not_required', max_length=20, verbose_name='قرار المراجعة'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employee_attendance', to=settings.AUTH_USER_MODEL, verbose_name='راجع السجل'),
        ),
    ]
