# Generated by Django 6.0.4 on 2026-04-26 11:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0008_employee_payroll_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='auto_calculate_hourly_rate',
            field=models.BooleanField(default=True, verbose_name='حساب سعر الساعة تلقائيًا'),
        ),
        migrations.AddField(
            model_name='employee',
            name='deduction_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='معامل الخصم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='معامل الإضافي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='required_daily_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ساعات الدوام اليومية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_break_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='الاستراحة بالدقائق'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='نهاية الدوام'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_grace_period_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='سماح التأخير بالدقائق'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='بداية الدوام'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الراتب الإجمالي حسب العقد'),
        ),
    ]
