# Generated by Django 6.0.4 on 2026-04-26 11:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0009_employee_auto_calculate_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم العطلة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=6, verbose_name='معامل إضافي العطلة')),
                ('is_paid', models.BooleanField(default=True, verbose_name='عطلة مدفوعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عطلة رسمية',
                'verbose_name_plural': 'العطل الرسمية',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='holiday_overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=6, verbose_name='معامل إضافي العطلة'),
        ),
    ]
