# Generated by Django 6.0.4 on 2026-07-10 19:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0011_alter_employeepermission_permission'),
        ('quick', '0016_quicksessionexcelimport_quicksessionexcelstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='شريك'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='partnership_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الشراكة (%)'),
        ),
        migrations.CreateModel(
            name='TeacherAcademicSalaryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('hourly', 'ساعي'), ('monthly', 'شهري ثابت'), ('mixed', 'مختلط (شهري + ساعي)')], default='hourly', max_length=20, verbose_name='نوع الراتب')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='أجر الساعة الأساسي')),
                ('hourly_rate_scientific', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='أجر الساعة علمي')),
                ('hourly_rate_literary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='أجر الساعة أدبي')),
                ('hourly_rate_ninth', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='أجر الساعة تاسع')),
                ('hourly_rate_preparatory', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='أجر الساعة تمهيدي')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='راتب شهري ثابت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick.academicyear', verbose_name='السنة الدراسية')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_salary_rates', to='employ.teacher')),
            ],
            options={
                'verbose_name': 'أجر المدرس السنوي',
                'verbose_name_plural': 'أجور المدرسين السنوية',
                'unique_together': {('teacher', 'academic_year')},
            },
        ),
    ]
