# Generated by Django 6.0.4 on 2026-07-14 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_transaction_dollar_amount'),
        ('employ', '0012_teacher_is_partner_teacher_partnership_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='partner_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_teachers', to='accounts.account', verbose_name='حساب الشريك الخاص'),
        ),
    ]
