# Generated by Django 4.2.7 on 2025-12-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='mobileuser',
            options={'verbose_name': 'مستخدم الموبايل', 'verbose_name_plural': 'مستخدمي الموبايل'},
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='api_announ_categor_ff76aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='emergencyalert',
            name='api_emergen_alert_t_02e8af_idx',
        ),
        migrations.RemoveIndex(
            model_name='mobileuser',
            name='api_mobileu_user_ty_e79cee_idx',
        ),
        migrations.RemoveIndex(
            model_name='mobileuser',
            name='api_mobileu_last_lo_1e5d89_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='api_announc_target__e432a5_idx',
            old_name='api_announ_target_849bf5_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='api_announc_publish_67e0a1_idx',
            old_name='api_announ_publish_1bb082_idx',
        ),
        migrations.RenameIndex(
            model_name='emergencyalert',
            new_name='api_emergen_user_id_50235e_idx',
            old_name='api_emergen_user_id_823909_idx',
        ),
        migrations.RenameIndex(
            model_name='emergencyalert',
            new_name='api_emergen_created_d22c65_idx',
            old_name='api_emergen_created_6cefee_idx',
        ),
        migrations.RenameIndex(
            model_name='mobileuser',
            new_name='api_mobileu_usernam_cb077e_idx',
            old_name='api_mobileu_usernam_d05026_idx',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='requires_acknowledgment',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='parent_response',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='student',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='viewed_by_parent',
        ),
        migrations.RemoveField(
            model_name='mobileuser',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='mobileuser',
            name='notification_enabled',
        ),
        migrations.RemoveField(
            model_name='mobileuser',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='alert_type',
            field=models.CharField(choices=[('emergency', 'حالة طارئة'), ('medical', 'طبي'), ('security', 'أمني'), ('general', 'عام')], default='emergency', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddIndex(
            model_name='mobileuser',
            index=models.Index(fields=['user_type'], name='api_mobileu_user_ty_0874f3_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileuser',
            index=models.Index(fields=['is_active'], name='api_mobileu_is_acti_afef08_idx'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
