# Generated by Django 4.2.7 on 2025-12-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_notification_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='api_announc_target__e432a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='api_announc_publish_67e0a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='emergencyalert',
            name='api_emergen_user_id_50235e_idx',
        ),
        migrations.RemoveIndex(
            model_name='emergencyalert',
            name='api_emergen_created_d22c65_idx',
        ),
        migrations.RemoveIndex(
            model_name='mobileuser',
            name='api_mobileu_usernam_cb077e_idx',
        ),
        migrations.RemoveIndex(
            model_name='mobileuser',
            name='api_mobileu_user_ty_0874f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='mobileuser',
            name='api_mobileu_is_acti_afef08_idx',
        ),
    ]
