# Generated by Django 4.2.27 on 2026-01-19 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quick', '0006_academicyear_is_open_ended'),
        ('classroom', '0001_initial'),
        ('accounts', '0006_costcenter_opening_balance'),
        ('pages', '0002_system_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemReportUserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('receipts_students_count', models.PositiveIntegerField(default=0)),
                ('receipts_students_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipts_quick_count', models.PositiveIntegerField(default=0)),
                ('receipts_quick_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expenses_count', models.PositiveIntegerField(default=0)),
                ('expenses_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('enrollments_students_count', models.PositiveIntegerField(default=0)),
                ('enrollments_quick_count', models.PositiveIntegerField(default=0)),
                ('attendance_students_count', models.PositiveIntegerField(default=0)),
                ('attendance_teachers_count', models.PositiveIntegerField(default=0)),
                ('teacher_sessions_count', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('teacher_half_sessions_count', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activity_total', models.PositiveIntegerField(default=0)),
                ('logins', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='pages.systemreport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportUserCourseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_quick', models.BooleanField(default=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.course')),
                ('quick_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick.quickcourse')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_receipts', to='pages.systemreport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportUserCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_quick', models.BooleanField(default=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.course')),
                ('quick_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick.quickcourse')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_enrollments', to='pages.systemreport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportTransactionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('debit_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_summary', to='pages.systemreport')),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportTopAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_addresses', to='pages.systemreport')),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_type', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('system', 'System')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pages.systemreport')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Report Request',
                'verbose_name_plural': 'System Report Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemReportDiscountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_receipts_count', models.PositiveIntegerField(default=0)),
                ('student_receipts_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('student_receipts_discount_percent_count', models.PositiveIntegerField(default=0)),
                ('quick_receipts_count', models.PositiveIntegerField(default=0)),
                ('quick_receipts_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quick_receipts_discount_percent_count', models.PositiveIntegerField(default=0)),
                ('enrollments_count', models.PositiveIntegerField(default=0)),
                ('enrollments_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('enrollments_discount_percent_count', models.PositiveIntegerField(default=0)),
                ('quick_enrollments_count', models.PositiveIntegerField(default=0)),
                ('quick_enrollments_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quick_enrollments_discount_percent_count', models.PositiveIntegerField(default=0)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_summary', to='pages.systemreport')),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportDiscountPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_percents', to='pages.systemreport')),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportCourseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(blank=True, max_length=20)),
                ('is_quick', models.BooleanField(default=False)),
                ('enrollments_count', models.PositiveIntegerField(default=0)),
                ('receipts_count', models.PositiveIntegerField(default=0)),
                ('receipts_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.course')),
                ('quick_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick.quickcourse')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_stats', to='pages.systemreport')),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_total', models.PositiveIntegerField(default=0)),
                ('students_active', models.PositiveIntegerField(default=0)),
                ('quick_students_total', models.PositiveIntegerField(default=0)),
                ('teachers_total', models.PositiveIntegerField(default=0)),
                ('employees_total', models.PositiveIntegerField(default=0)),
                ('users_total', models.PositiveIntegerField(default=0)),
                ('users_active', models.PositiveIntegerField(default=0)),
                ('users_staff', models.PositiveIntegerField(default=0)),
                ('users_superusers', models.PositiveIntegerField(default=0)),
                ('users_logged_in', models.PositiveIntegerField(default=0)),
                ('classrooms_total', models.PositiveIntegerField(default=0)),
                ('subjects_total', models.PositiveIntegerField(default=0)),
                ('courses_total', models.PositiveIntegerField(default=0)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counts_snapshot', to='pages.systemreport')),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportClassroomStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_total', models.PositiveIntegerField(default=0)),
                ('students_in_period', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.classroom')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_stats', to='pages.systemreport')),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportAttendanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_records', models.PositiveIntegerField(default=0)),
                ('teachers_records', models.PositiveIntegerField(default=0)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to='pages.systemreport')),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_summary', to='pages.systemreport')),
            ],
        ),
        migrations.CreateModel(
            name='SystemReportActivityAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_actions', to='pages.systemreport')),
            ],
        ),
    ]
