# Generated by Django 4.2.27 on 2026-01-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_systemreportuserstats_systemreportusercoursereceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemreportuserstats',
            name='active_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='systemreportuserstats',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemreportuserstats',
            name='created_quick_students_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemreportuserstats',
            name='created_students_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
