# Generated by Django 4.2.27 on 2026-01-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_systemreportuserstats_active_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemreportcoursestats',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='systemreportcoursestats',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='systemreportcoursestats',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='systemreportcoursestats',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='SystemReportDiscountRuleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('rule_name', models.CharField(max_length=200)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_rule_usages', to='pages.systemreport')),
            ],
        ),
    ]
