# Generated by Django 4.2.27 on 2026-03-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_userclickevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclickevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
