# Generated by Django 4.2.27 on 2026-03-13 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_userclickevent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmailReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('time_of_day', models.TimeField(default=datetime.time(19, 0))),
                ('recipient_emails', models.TextField(blank=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Daily Email Report Schedule',
                'verbose_name_plural': 'Daily Email Report Schedules',
            },
        ),
        migrations.AddField(
            model_name='activitylog',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
