# Generated by Django 6.0.4 on 2026-07-15 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_dailyemailreportschedule_activitylog_extra_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='القسم')),
                ('completed_tasks', models.TextField(blank=True, verbose_name='المهام المنجزة')),
                ('problems', models.TextField(blank=True, verbose_name='المشاكل إن وجدت')),
                ('suggestions', models.TextField(blank=True, verbose_name='المقترحات')),
                ('auto_attendance_info', models.TextField(blank=True, verbose_name='معلومات الحضور التلقائية')),
                ('auto_exam_info', models.TextField(blank=True, verbose_name='معلومات الامتحانات التلقائية')),
                ('auto_cash_info', models.TextField(blank=True, verbose_name='معلومات الصندوق التلقائية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تقرير الموظف اليومي',
                'verbose_name_plural': 'تقارير الموظفين اليومية',
                'ordering': ['-date', 'user'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
