# Generated by Django 5.0.14 on 2025-11-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='actual_annual_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المصروف الفعلي السنوي / Actual Annual Spent'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='actual_monthly_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المصروف الفعلي الشهري / Actual Monthly Spent'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء / End Date'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد المدير / Manager Email'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البدء / Start Date'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='target_profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='هامش الربح المستهدف % / Target Profit Margin %'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='target_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإيراد المستهدف / Target Revenue'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='cost_center_type',
            field=models.CharField(choices=[('ACADEMIC', 'أكاديمي / Academic'), ('ADMINISTRATIVE', 'إداري / Administrative'), ('OPERATIONAL', 'تشغيلي / Operational'), ('SUPPORT', 'دعم / Support'), ('MARKETING', 'تسويقي / Marketing')], default='ACADEMIC', max_length=20, verbose_name='نوع مركز التكلفة / Cost Center Type'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['code'], name='accounts_co_code_db83ba_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['cost_center_type'], name='accounts_co_cost_ce_49607c_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['is_active'], name='accounts_co_is_acti_bc6d77_idx'),
        ),
    ]
