# Generated by Django 5.0.14 on 2025-11-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_costcenter_actual_annual_spent_and_more'),
        ('quick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickCourseAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.PositiveIntegerField(default=0, verbose_name='إجمالي التسجيلات')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الإيرادات')),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المحصل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quick.quickcourse', verbose_name='الدورة السريعة')),
                ('deferred_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='حساب الإيرادات المؤجلة')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_revenue', to='accounts.account', verbose_name='حساب الإيرادات')),
            ],
            options={
                'verbose_name': 'محاسبة دورة سريعة',
                'verbose_name_plural': 'محاسبة الدورات السريعة',
            },
        ),
        migrations.CreateModel(
            name='QuickStudentAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.PositiveIntegerField(default=0, verbose_name='إجمالي التسجيلات')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الإيرادات')),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المحصل')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد المتبقي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ar_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='حساب الذمم')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quick.quickstudent', verbose_name='الطالب السريع')),
            ],
            options={
                'verbose_name': 'محاسبة طالب سريع',
                'verbose_name_plural': 'محاسبة الطلاب السريعين',
            },
        ),
    ]
