# Generated by Django 5.0.14 on 2025-11-18 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_quickcourseaccounting_quickstudentaccounting'),
        ('quick', '0003_quickenrollment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreceipt',
            name='quick_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick.quickenrollment', verbose_name='التسجيل السريع'),
        ),
    ]
