# Generated by Django 5.0.14 on 2025-11-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentreceipt_quick_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رصيد الافتتاح'),
        ),
    ]
