# Generated by Django 6.0.4 on 2026-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_financial_academic_year_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='سبب الحسم / Discount Reason'),
        ),
    ]
