# Generated by Django 6.0.4 on 2026-06-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentenrollment_discount_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='subjects_note',
            field=models.CharField(default='كامل المواد', max_length=255, verbose_name='المواد المسجلة / Registered Subjects'),
        ),
    ]
