# Generated by Django 4.2.30 on 2026-07-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_studentenrollment_subjects_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account', verbose_name='حساب البنك الافتراضي')),
                ('default_cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account', verbose_name='حساب الصندوق الافتراضي')),
                ('default_deferred_revenue_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account', verbose_name='الحساب الأب للإيرادات المؤجلة')),
                ('default_student_ar_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account', verbose_name='الحساب الأب لذمم الطلاب')),
                ('default_withdrawal_revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account', verbose_name='حساب إيرادات الانسحاب')),
            ],
            options={
                'verbose_name': 'إعدادات الحسابات / Accounting Settings',
                'verbose_name_plural': 'إعدادات الحسابات / Accounting Settings',
            },
        ),
    ]
