# Generated by Django 6.0.4 on 2026-07-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_transaction_dollar_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dollar_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='مبلغ الدولار / Dollar Amount'),
        ),
    ]
