# Generated by Django 4.2.27 on 2025-12-23 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employ', '0004_alter_employeepermission_permission_and_more'),
        ('classroom', '0001_initial'),
        ('students', '0005_studentwarning'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاختبار')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_tests', to='classroom.classroom', verbose_name='الشعبة')),
            ],
            options={
                'verbose_name': 'اختبار تسميع',
                'verbose_name_plural': 'اختبارات التسميع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('attendance', 'حضور'), ('payment', 'دفع'), ('warning', 'إنذار'), ('exam', 'اختبار'), ('test_assignment', 'تسميع')], max_length=30, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم قراءته')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_notifications', to='students.student', verbose_name='الطالب')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employ.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'إشعار موبايل',
                'verbose_name_plural': 'إشعارات الموبايل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_listened', models.BooleanField(default=False, verbose_name='تم التسميع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإعلان')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_assignments', to='students.student', verbose_name='الطالب')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mobile.listeningtest', verbose_name='اختبار')),
            ],
            options={
                'verbose_name': 'حالة تسميع',
                'verbose_name_plural': 'حالات التسميع',
                'unique_together': {('test', 'student')},
            },
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='students',
            field=models.ManyToManyField(through='mobile.ListeningTestAssignment', to='students.student', verbose_name='الطلاب'),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_tests', to='employ.teacher', verbose_name='المدرس'),
        ),
    ]
