# Generated by Django 4.2.27 on 2025-12-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtestassignment',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='العلامة'),
        ),
        migrations.AddField(
            model_name='listeningtestassignment',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة'),
        ),
    ]
