# Generated by Django 4.2.27 on 2026-01-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_mobiledevicetoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobiledevicetoken',
            new_name='mobile_mobi_user_ty_9178b4_idx',
            old_name='mobiledevi_user_ty_8d20c9_idx',
        ),
        migrations.AlterField(
            model_name='mobiledevicetoken',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledevicetoken',
            name='user_type',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('parent', 'Parent')], max_length=20, null=True),
        ),
    ]
