# Generated by Codex on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0005_listeningtest_max_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobiledevicetoken",
            name="login_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("parent", "Parent"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mobiledevicetoken",
            name="device_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]

