# Generated by Django 4.2.27 on 2026-03-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_mobiledevicetoken_login_role_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledevicetoken',
            name='user_type',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
