# Generated by Django 5.0.14 on 2025-11-23 17:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0002_student_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الاختبار')),
                ('exam_date', models.DateField(verbose_name='تاريخ الاختبار')),
                ('max_exams', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='العلامة القصوى')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom', verbose_name='الشعبة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
                'ordering': ['-exam_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Examexams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exams', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='العلامة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='الاختبار')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'علامة اختبار',
                'verbose_name_plural': 'علامات الاختبارات',
                'ordering': ['student__full_name'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('activity', 'نشاط'), ('monthly', 'شهري'), ('midterm', 'نصفي'), ('final', 'نهائي')], max_length=20, verbose_name='نوع الامتحان')),
                ('exams', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='العلامة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom', verbose_name='الشعبة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examss', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'علامة',
                'verbose_name_plural': 'العلامات',
                'ordering': ['-date', 'student__full_name'],
                'unique_together': {('student', 'subject', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الاختبار')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب الظهور')),
                ('max_exams', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='العلامة القصوى')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'نوع اختبار',
                'verbose_name_plural': 'أنواع الاختبارات',
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'subject')},
            },
        ),
    ]
