# Generated by Django 5.0.14 on 2025-11-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0002_student_academic_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examexams',
            new_name='ExamGrade',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='max_exams',
            new_name='max_grade',
        ),
        migrations.RenameField(
            model_name='examgrade',
            old_name='exams',
            new_name='grade',
        ),
    ]
