# Generated by Django 5.0.14 on 2025-11-24 11:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('courses', '0001_initial'),
        ('exams', '0002_rename_examexams_examgrade_and_more'),
        ('students', '0004_alter_student_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtype',
            old_name='max_exams',
            new_name='max_grade',
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('activity', 'نشاط'), ('monthly', 'شهري'), ('midterm', 'نصفي'), ('final', 'نهائي')], max_length=20, verbose_name='نوع الامتحان')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='العلامة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom', verbose_name='الشعبة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'علامة',
                'verbose_name_plural': 'العلامات',
                'ordering': ['-date', 'student__full_name'],
                'unique_together': {('student', 'subject', 'exam_type')},
            },
        ),
        migrations.DeleteModel(
            name='exams',
        ),
    ]
