# Generated by Django 6.0.4 on 2026-07-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_rename_max_exams_examtype_max_grade_studentexam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.examtype', verbose_name='نوع الاختبار'),
        ),
        migrations.AddField(
            model_name='examgrade',
            name='status',
            field=models.CharField(choices=[('present', 'مقدم / Present'), ('absent', 'غائب / Absent'), ('not_submitted', 'غير مقدم / Not Submitted')], default='present', max_length=20, verbose_name='حالة التقديم'),
        ),
    ]
