# Generated by Django 5.0.14 on 2025-11-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_passwordresetrequest_delete_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='سيتم ضغط الصورة تلقائياً لتقليل الحجم', null=True, upload_to='profile_pictures/'),
        ),
    ]
