# Generated by Django 5.0.14 on 2025-11-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_passwordchangehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangehistory',
            name='new_password_hash',
            field=models.CharField(max_length=128, verbose_name='كلمة المرور الجديدة'),
        ),
        migrations.AlterField(
            model_name='passwordchangehistory',
            name='old_password_hash',
            field=models.CharField(max_length=128, verbose_name='كلمة المرور القديمة'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
