# Generated by Django 4.2.11 on 2025-12-09 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classroom", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroomenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_enrollments",
                to="students.student",
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classroomsubject",
            unique_together={("classroom", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="classroomenrollment",
            unique_together={("classroom", "student")},
        ),
    ]
