# Generated by Django 4.2.27 on 2026-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='الحد الأقصى'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='min_capacity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='الحد الأدنى'),
        ),
    ]
