# Generated by Django 6.0.4 on 2026-05-30 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentenrollment_discount_reason'),
        ('classroom', '0003_classroom_max_capacity_classroom_min_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='accounts.course', verbose_name='الدورة المرتبطة'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='تحديد ما إذا كانت هذه الشعبة مرئية لباقي المستخدمين غير السوبر يوزر.', verbose_name='مرئية لباقي المستخدمين'),
        ),
    ]
