# Generated by Django 4.2.30 on 2026-06-24 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150, verbose_name='المسمى الوظيفي')),
                ('department', models.CharField(max_length=150, verbose_name='القسم')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التقرير')),
                ('incident_date', models.DateField(verbose_name='تاريخ وقوع المشكلة')),
                ('report_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم التقرير')),
                ('issue_description', models.TextField(verbose_name='وصف المشكلة')),
                ('issue_impact', models.TextField(blank=True, null=True, verbose_name='تأثير المشكلة')),
                ('code_solution', models.TextField(blank=True, null=True, verbose_name='الحل البرمجي المطبق')),
                ('employee_instructions', models.TextField(blank=True, null=True, verbose_name='ما يجب على الموظف القيام به')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='توصيات وملاحظات')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تقرير مشكلة تقنية',
                'verbose_name_plural': 'تقارير المشاكل التقنية',
                'ordering': ['-report_date', '-id'],
            },
        ),
    ]
