# Generated by Django 5.0.14 on 2025-11-08 22:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('classroom', '0001_initial'),
        ('employ', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر')], default='absent', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom', verbose_name='الشعبة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'سجل الحضور',
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('no_duty', 'ليس لديه دوام اليوم')], default='no_duty', max_length=10, verbose_name='الحالة')),
                ('session_count', models.PositiveIntegerField(default=0, verbose_name='عدد الجلسات الكاملة')),
                ('half_session_count', models.PositiveIntegerField(default=0, help_text='عدد أنصاف الجلسات (كل نصف جلسة = 0.5 جلسة)', verbose_name='عدد أنصاف الجلسات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('salary_accrual_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.journalentry', verbose_name='قيد الراتب المرتبط')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employ.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'حضور مدرس',
                'verbose_name_plural': 'سجل حضور المدرسين',
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
