# Generated by Django 4.2.7 on 2025-12-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_add_half_session_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherattendance',
            name='salary_accrual_entry',
        ),
    ]
