# Generated by Django 4.2.27 on 2026-01-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0005_teacher_hourly_rate_literary_and_more'),
        ('attendance', '0003_remove_teacherattendance_salary_accrual_entry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='branch',
            field=models.CharField(choices=[('أدبي', 'أدبي'), ('علمي', 'علمي'), ('تاسع', 'الصف التاسع'), ('تمهيدي', 'التمهيدي')], default='علمي', max_length=20, verbose_name='Branch'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('teacher', 'date', 'branch')},
        ),
    ]
